version: '2'
services:
  jenkins:
    build: 
      context: .
    container_name: 'jenkins_container'
    restart: 'always'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
volumes:
  jenkins_data:
    driver: local
